name: Run Azure Login with OpenID Connect
on: [workflow_dispatch]

permissions:
      id-token: write
      contents: read
      
jobs: 
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 9_azure_oidc

    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: PWD
      run: echo $PWD
    
    - name: List Directory 
      run: ls -atrl
    
    - name: Terraform Init
      id: init
      run: terraform init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
